apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubexplain

commonLabels:
  app.kubernetes.io/name: kubexplain
  app.kubernetes.io/part-of: kubexplain

resources:
  - namespace.yaml
  - postgres-config.yaml
  - postgres-init-configmap.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - ai-server-service.yaml
  - ai-server-deployment.yaml
  - ollama-service.yaml
  - ollama-deployment.yaml
  - elasticsearch-service.yaml
  - elasticsearch-deployment.yaml