import { initNavigation } from './navigation.js';
import { initModals } from './modals.js';
import { initAttachments } from './attachments.js';
import { initResourcePicker } from './resourcePicker.js';
import { initChat } from './chat.js';
import { initPodsScanner } from './pods.js';
import { initNodesScanner } from './nodes.js';
import { initAuth } from './auth.js';
import { initClusterManager } from './clusters.js';
import { initTopology } from './topology.js';
import { initTheme } from './theme.js';
import { initUI } from './ui.js';
import { initPreferences } from './preferences.js';
import { restoreSession } from './session.js';

document.addEventListener('DOMContentLoaded', () => {
  initTheme();
  initPreferences();
  initAuth();
  initNavigation();
  initModals();
  initAttachments();
  initResourcePicker();
  initChat();
  initPodsScanner();
  initNodesScanner();
  initClusterManager();
  initTopology();
  initUI();
  restoreSession();
});
